// All sauce data — accessed as window.SD globally
window.SD = {
  cats:[
    {id:"w",nm:"White Sauces",fr:"Sauces Blanches",ic:"🤍",subs:[
      {nm:"Veal Velouté",mo:"Velouté — veal",s:["Allemande Grasse","Poulette","Villageoise","Tarragon Sauce","Villeroi"]},
      {nm:"Poultry Velouté",mo:"Velouté — poultry",s:["Supreme","Aurora","Albufera","Ivory"]},
      {nm:"Fish Velouté",mo:"Velouté — fish",s:["Bercy Fish","Normandy","Cardinal","Marinière","Saint-Malo","Veron","Genevoise"]},
      {nm:"Béchamel",mo:"Béchamel — milk",s:["Mornay","Soubise","Nantua"]}
    ]},
    {id:"b",nm:"Brown Sauces",fr:"Sauces Brunes",ic:"🟤",subs:[
      {nm:"Espagnole / Demi-glace",mo:"Espagnole",s:["Bordelaise","Madeira","Porto","Chateaubriand","Périgueux","Robert","Piquante","Diable","Sainte-Menehould","Zingara","Financière"]},
      {nm:"Brown Poultry",mo:"Brown poultry stock",s:["Chasseur","Bigarade","Rouennaise"]},
      {nm:"Game Stock",mo:"Brown game stock",s:["Poivrade","Grand Veneur","Chevreuil"]},
      {nm:"Tomato",mo:"Tomat",s:["Tomato","Bolognese","Tomato Purée","Tomato Coulis"]}
    ]},
    {id:"he",nm:"Hot Emulsified",fr:"Émulsionnées Chaudes",ic:"🫧",subs:[
      {nm:"Béarnaise Family",mo:"Béarnaise",s:["Béarnaise","Choron","Foyot","Paloise"]},
      {nm:"Hollandaise Family",mo:"Hollandaise",s:["Hollandaise","Mousseline","Maltese"]},
      {nm:"Butter Emulsions",mo:"Butter",s:["Beurre Blanc","Beurre Nantais"]}
    ]},
    {id:"ce",nm:"Cold Emulsified",fr:"Émulsionnées Froides",ic:"❄️",subs:[
      {nm:"Mayonnaise Family",mo:"Mayonnaise",s:["Mayonnaise","Remoulade","Tartar","Gribiche","Cold Andalusian","Aioli","Rouille"]},
      {nm:"Vinaigrette Family",mo:"Vinaigrette",s:["Vinaigrette","Mustard Vinaigrette","Ravigote","Lemonette"]}
    ]},
    {id:"cs",nm:"Cold Sauces",fr:"Sauces Froides",ic:"🌿",subs:[
      {nm:"Cold Miscellaneous",mo:"Various",s:["Cumberland","Yorkshire","Cambridge","Cold Russian","Sarladaise","Mint Sauce"]}
    ]},
    {id:"ds",nm:"Dessert Sauces",fr:"Sauces Dessert",ic:"🍮",subs:[
      {nm:"Sweet Sauces",mo:"Dessert",s:["Caramel","Blackcurrant","Chocolate","Cranberry","Apple Sauce"]}
    ]}
  ],
  usage:{
    "Fish / Seafood":["Albufera","Cardinal","Hollandaise","Maltese","Marinière","Nantua","Normandy","Remoulade","Ravigote","Bercy Fish","Genevoise","Poulette","Cold Andalusian","Veron"],
    "Meat":["Béarnaise","Bordelaise","Bolognese","Chateaubriand","Choron","Cumberland","Diable","Foyot","Madeira","Mornay","Mousseline","Poivrade","Robert","Supreme","Tomato","Zingara","Yorkshire"],
    "Poultry":["Albufera","Aurora","Chasseur","Financière","Poulette","Supreme","Villeroi","Allemande Grasse"],
    "Game":["Chevreuil","Cumberland","Grand Veneur","Poivrade","Rouennaise","Zingara"],
    "Vegetables / Eggs":["Bechamel","Gribiche","Hollandaise","Mornay","Mint Sauce","Soubise","Tartar"],
    "Dessert":["Caramel","Blackcurrant","Chocolate","Cranberry","Apple Sauce"],
    "Cold Sauces":["Cold Andalusian","Cumberland","Gribiche","Mint Sauce","Ravigote","Remoulade","Cold Russian","Tartar","Yorkshire"],
    "Hot Sauces":["Béarnaise","Bordelaise","Chasseur","Diable","Hollandaise","Madeira","Normandy","Supreme"]
  },
  cico:{"White Sauces":"🤍","Brown Sauces":"🟤","Hot Emulsified":"🫧","Cold Emulsified":"❄️","Cold Sauces":"🌿","Dessert Sauces":"🍮"},
  uico:{"Fish / Seafood":"🐟","Meat":"🥩","Poultry":"🍗","Game":"🦌","Vegetables / Eggs":"🥦","Dessert":"🍮","Cold Sauces":"🌿","Hot Sauces":"🔥"},
  tico:{"Emulsified (Hot)":"🌡️","Emulsified (Cold)":"❄️","Roux-based":"🥛","Reduction":"⬇️","Tomato-based":"🍅","Fruit-based":"🍊","Unstable Emulsion":"🫗","Dessert":"🍮"},
  r:{
    "Béarnaise":{nm:"Béarnaise Sauce",fr:"Sauce Béarnaise",cat:"Hot Emulsified",mo:"Béarnaise",tp:"Emulsified",tm:"Hot",bs:"Butter/Egg",df:"Medium",ti:"30 min",pr:["steak","eggs","asparagus","veal","fish"],ig:{base:["egg yolks (5)","clarified butter (250g)"],aromatics:["shallots (50g)","tarragon (3 tbsp)","chervil (1 tbsp)"],acid:["tarragon vinegar (10cl)","dry white wine (5cl)"],finish:["fresh tarragon","chervil","salt","cracked pepper"]},st:["Reduce vinegar, wine, shallots, tarragon, chervil, pepper by ⅔. Cool.","Add 5 egg yolks + cold water. Whisk over low heat 55°C.","Remove from heat, gradually incorporate 250g warm clarified butter.","Strain through chinois, finish with fresh tarragon and chervil."],dv:["Choron","Foyot","Paloise"],sm:["Hollandaise","Foyot","Choron"],rc:"Reduce 10cl tarragon vinegar, 5cl dry white wine, 50g finely chopped shallots, 3 tbsp chopped tarragon, 1 tbsp chervil, 5g cracked pepper and a pinch of salt by two-thirds. Cool. Add 5 egg yolks and a little water; whisk vigorously over low heat (55°C). Remove from heat, gradually incorporate 250g warm clarified butter. Strain through a chinois and finish with 1 tbsp each chopped tarragon and chervil. Serve immediately."},
    "Hollandaise":{nm:"Hollandaise Sauce",fr:"Sauce Hollandaise",cat:"Hot Emulsified",mo:"Hollandaise",tp:"Emulsified",tm:"Hot",bs:"Butter/Egg",df:"Medium",ti:"15 min",pr:["fish","eggs","asparagus","vegetables","poultry"],ig:{base:["egg yolks (5)","clarified butter (300g)"],acid:["lemon juice (½, optional)"],finish:["fine salt","white pepper"]},st:["Clarify butter, keep warm. Combine yolks with 3 tbsp cold water, season.","Place in bain-marie, heat gradually, whisk vigorously until foamy and creamy.","Remove, whisk to cool slightly. Gradually incorporate warm clarified butter.","Strain. Keep at max 55°C."],dv:["Mousseline","Maltese"],sm:["Béarnaise","Mousseline","Maltese"],rc:"Clarify 300g butter and keep warm. Combine 5 egg yolks with 3 tbsp cold water, fine salt and white pepper in a bain-marie. Heat gradually, whisking vigorously until the mixture foams and thickens to a cream. Remove, whisk to cool slightly. Gradually pour in warm clarified butter. Strain. Keep at max 55°C."},
    "Bechamel":{nm:"Béchamel Sauce",fr:"Sauce Béchamel",cat:"White Sauces",mo:"Béchamel",tp:"Roux-based",tm:"Hot",bs:"Milk",df:"Easy",ti:"15 min",pr:["pasta","vegetables","eggs","poultry","fish"],ig:{base:["butter (60g)","flour (60g)","milk (1L)"],aromatics:["nutmeg, grated"],finish:["fine salt","cayenne pepper"]},st:["Melt butter, add flour, cook 1 min without browning. Cool.","Bring milk to boil, pour gradually over cold roux, whisk constantly.","Bring to boil, cook 4–5 min. Season.","Strain. Dot with butter to prevent skin."],dv:["Mornay","Soubise","Nantua"],sm:["Mornay","Soubise"],rc:"Melt 60g butter, add 60g flour; mix to a smooth paste. Cook over low heat 1 minute (white roux). Cool. Bring 1 litre milk to the boil, pour gradually over cold roux, whisking constantly. Bring to boil, cook 4–5 minutes. Season with fine salt, cayenne and grated nutmeg. Strain."},
    "Bordelaise":{nm:"Bordelaise Sauce",fr:"Sauce Bordelaise",cat:"Brown Sauces",mo:"Demi-glace",tp:"Reduction",tm:"Hot",bs:"Demi-glace",df:"Medium",ti:"30 min",pr:["steak","beef","veal","lamb"],ig:{base:["demi-glace (20cl)","red wine (20cl)"],aromatics:["shallot (1 tbsp)","thyme","bay leaf"],finish:["bone marrow, poached (25g)","butter (25g)","parsley (1 tsp)"]},st:["Cube and poach bone marrow; drain.","Reduce shallot with red wine, thyme, bay, salt by ⅔.","Add demi-glace, reduce by ⅓. Off heat, add butter and strain.","Add bone marrow and parsley at last moment."],sm:["Madeira","Robert","Périgueux"],rc:"Cut 25g bone marrow into cubes, drain then poach. Reduce 1 tbsp chopped shallot with 20cl red wine, thyme, bay leaf and a pinch of salt by two-thirds. Add 20cl demi-glace and reduce by one-third. Off heat, add 25g butter and strain. Add the bone marrow and 1 tsp chopped parsley."},
    "Madeira":{nm:"Madeira Sauce",fr:"Sauce Madère",cat:"Brown Sauces",mo:"Demi-glace",tp:"Reduction",tm:"Hot",bs:"Brown veal stock",df:"Medium",ti:"60 min",pr:["beef","veal","ham","mushrooms","foie gras"],ig:{base:["brown veal stock (1L)","Madeira wine (10cl + 1 tsp)"],aromatics:["shallot (1 tbsp)","celery (2 stalks)","garlic (1 clove)","tomatoes (200g)","tomato paste (1 tbsp)"],finish:["butter (10g)","salt","pepper"]},st:["Prepare flavored veal stock. Strain, reduce by ¾.","Reduce shallot with 10cl Madeira by ⅔. Add reduced stock.","Simmer 10 min, skim. Strain, season.","Add 1 tsp Madeira, finish with butter."],sm:["Bordelaise","Périgueux"],rc:"Prepare 1 litre brown veal stock with celery, garlic, tomatoes and tomato paste. Strain and reduce by three-quarters. Reduce 1 tbsp finely chopped shallot with 10cl Madeira by two-thirds; add reduced stock. Simmer 10 minutes. Strain, season. Add 1 tsp Madeira and finish by whisking in 10g butter."},
    "Choron":{nm:"Choron Sauce",fr:"Sauce Choron",cat:"Hot Emulsified",mo:"Béarnaise",tp:"Emulsified",tm:"Hot",bs:"Béarnaise",df:"Medium",ti:"35 min",pr:["steak","eggs","fish","veal"],ig:{base:["béarnaise sauce (20cl)"],finish:["tomato purée, very reduced (2 tbsp)"]},st:["Prepare béarnaise sauce.","Add warm, very reduced and sieved tomato purée."],sm:["Béarnaise","Foyot"],rc:"Add 20cl béarnaise sauce to 2 tbsp of warm tomato purée, very reduced and passed through a sieve."},
    "Foyot":{nm:"Foyot Sauce (Valois)",fr:"Sauce Foyot / Valois",cat:"Hot Emulsified",mo:"Béarnaise",tp:"Emulsified",tm:"Hot",bs:"Béarnaise",df:"Medium",ti:"35 min",pr:["steak","veal","sweetbreads"],ig:{base:["béarnaise sauce (20cl)"],finish:["meat glaze (2 tbsp)"]},st:["Prepare béarnaise sauce and strain.","Stir in 2 tbsp of meat glaze."],sm:["Béarnaise","Choron"],rc:"Prepare 20cl béarnaise sauce. Strain and add 2 tablespoons of meat glaze, stirring."},
    "Mousseline":{nm:"Mousseline Sauce",fr:"Sauce Mousseline",cat:"Hot Emulsified",mo:"Hollandaise",tp:"Emulsified",tm:"Hot",bs:"Hollandaise",df:"Medium",ti:"20 min",pr:["asparagus","fish","vegetables","eggs"],ig:{base:["hollandaise sauce (20cl)"],finish:["firm whipped cream"]},st:["Prepare hollandaise sauce, keep tight.","At moment of serving, fold in firm whipped cream."],sm:["Hollandaise","Maltese"],rc:"Prepare a tight hollandaise sauce and fold in firm whipped cream when ready to serve."},
    "Maltese":{nm:"Maltese Sauce",fr:"Sauce Maltaise",cat:"Hot Emulsified",mo:"Hollandaise",tp:"Emulsified",tm:"Hot",bs:"Hollandaise",df:"Medium",ti:"20 min",pr:["asparagus","fish","vegetables"],ig:{base:["hollandaise sauce (20cl)"],acid:["orange juice (½ orange)"],finish:["orange zest, blanched julienne (1 orange)"]},st:["Prepare hollandaise sauce.","Blanch orange zest into fine julienne strips.","Add warm orange juice and blanched zest to hollandaise."],sm:["Hollandaise","Mousseline"],rc:"Prepare a Hollandaise sauce. Cut the zest of 1 orange into very fine julienne strips and blanch thoroughly. Add the warm orange juice and blanched zest to the Hollandaise."},
    "Mornay":{nm:"Mornay Sauce",fr:"Sauce Mornay",cat:"White Sauces",mo:"Béchamel",tp:"Roux-based",tm:"Hot",bs:"Milk",df:"Easy",ti:"20 min",pr:["pasta","vegetables","eggs","fish","poultry"],ig:{base:["béchamel (50cl)","gruyère, grated (70g)"],finish:["egg yolks (2)","cream (optional)"]},st:["Heat béchamel.","Off heat, add beaten egg yolks with cream. Reheat briefly.","Fold in sifted grated gruyère without whisking."],sm:["Béchamel","Soubise","Nantua"],rc:"Heat 50cl béchamel. Off the heat, add 2 beaten egg yolks with a little cream. Reheat briefly. Fold in 70g sifted grated Gruyère without whisking. Tamponner."},
    "Soubise":{nm:"Soubise Sauce",fr:"Sauce Soubise",cat:"White Sauces",mo:"Béchamel",tp:"Roux-based",tm:"Hot",bs:"Milk/Onion",df:"Easy",ti:"60 min",pr:["lamb","veal","eggs","vegetables"],ig:{base:["thick béchamel","white onions (1kg)","butter (100g)"],aromatics:["pinch of sugar"],finish:["butter (75g)","double cream (10cl)"]},st:["Blanch onions. Sweat in butter 30–40 min without browning.","Add thick béchamel, cook 20 min more.","Pass through very fine sieve. Finish with butter and cream."],sm:["Béchamel","Mornay"],rc:"Blanch 1kg thinly sliced white onions. Sweat in 100g butter, covered, 30–40 min without browning. Add one-quarter volume of thick béchamel, cook 20 min more. Pass through a very fine sieve. Finish with 75g butter and 10cl double cream."},
    "Supreme":{nm:"Supreme Sauce",fr:"Sauce Suprême",cat:"White Sauces",mo:"Velouté (poultry)",tp:"Roux-based",tm:"Hot",bs:"Poultry stock",df:"Medium",ti:"45 min",pr:["poultry","veal","mushrooms","eggs"],ig:{base:["white poultry velouté","crème fraîche (30–40cl)"],finish:["butter (50g)"]},st:["Prepare rich white poultry velouté. Reduce by at least half.","Add crème fraîche, reduce until 60cl remains.","Off heat, add butter. Strain."],dv:["Aurora","Albufera"],sm:["Aurora","Albufera"],rc:"Prepare a velouté with a white roux and well-flavored white poultry stock. Reduce by at least half. Add 30–40cl crème fraîche and reduce until 60cl remains. Off the heat, add 50g butter. Strain."},
    "Allemande Grasse":{nm:"Allemande Sauce",fr:"Sauce Allemande Grasse",cat:"White Sauces",mo:"Velouté (veal)",tp:"Roux-based",tm:"Hot",bs:"White veal stock",df:"Medium",ti:"40 min",pr:["veal","poultry","mushrooms"],ig:{base:["white veal stock (40cl)","velouté (50cl)","egg yolks (3–4)"],aromatics:["mushroom liquid (10cl)","lemon juice","pepper","nutmeg"],finish:["fresh butter (50g)"]},st:["Combine stock, mushroom liquid, lemon, pepper, nutmeg and velouté. Reduce.","Off heat, add egg yolk liaison. Return to boil.","Strain through muslin-lined chinois, incorporate butter."],dv:["Poulette","Villeroi"],rc:"Combine 40cl white veal stock, 10cl mushroom cooking liquid, lemon juice, crushed peppercorns, pinch of nutmeg, and 50cl velouté. Reduce. Off the heat, add a liaison of 3–4 egg yolks loosened with a little velouté. Return to the boil, strain through a muslin-lined chinois, and finish with 50g fresh butter."},
    "Normandy":{nm:"Normandy Sauce",fr:"Sauce Normande",cat:"White Sauces",mo:"Velouté (fish)",tp:"Roux-based",tm:"Hot",bs:"Fish stock",df:"Medium",ti:"30 min",pr:["sole","turbot","fish","oysters","mussels"],ig:{base:["sole velouté (20cl)","fish fumet (10cl)","mushroom liquid (10cl)"],finish:["egg yolks (2)","cream (5 tbsp)","butter (50g)"]},st:["Heat sole velouté, fish fumet and mushroom liquid.","Beat yolks with 2 tbsp cream, add to pan, reduce by ⅓.","Add butter in pieces and 3 tbsp thick cream."],sm:["Bercy Fish","Cardinal"],rc:"Heat 20cl sole velouté, 10cl fish fumet, and 10cl mushroom cooking liquid. Beat 2 egg yolks with 2 tbsp cream, add to pan, and reduce by one-third. Add 50g butter in pieces and 3 tbsp thick cream."},
    "Cardinal":{nm:"Cardinal Sauce",fr:"Sauce Cardinal",cat:"White Sauces",mo:"Velouté (fish)",tp:"Roux-based",tm:"Hot",bs:"Fish stock",df:"Medium",ti:"30 min",pr:["lobster","fish","seafood"],ig:{base:["lean velouté (20cl)","fish stock (10cl)","cream (10cl)"],aromatics:["truffle or truffle essence (1 tbsp)"],finish:["lobster butter (50g)","cayenne pepper"]},st:["Reduce velouté maigre and fish stock by half.","Add cream, stir. Off heat, stir in lobster butter.","Season with cayenne and strain. Flavor with truffle."],sm:["Nantua","Normandy"],rc:"Reduce 20cl velouté maigre and 10cl fish stock by half. Add 10cl cream. Off the heat, stir in 50g lobster butter. Season with cayenne, strain, and flavor with truffle essence."},
    "Nantua":{nm:"Nantua Sauce",fr:"Sauce Nantua",cat:"White Sauces",mo:"Béchamel",tp:"Roux-based",tm:"Hot",bs:"Milk/Crayfish",df:"Medium",ti:"45 min",pr:["fish","quenelles","seafood","eggs"],ig:{base:["béchamel or fish velouté","cooked crayfish","cream"],acid:["cognac (1 tsp)","cayenne"],finish:["crayfish butter (100g)"]},st:["Combine béchamel/velouté, crayfish, cream in equal parts. Reduce by ⅓.","Whisk in crayfish butter, cognac, cayenne. Strain."],sm:["Cardinal","Mornay"],rc:"Prepare a béchamel or light fish velouté. Add equal amounts of cooked crayfish and cream. Reduce by a third. Whisk 100g crayfish butter, 1 tsp cognac and a dash of cayenne into the boiling mixture. Strain."},
    "Aurora":{nm:"Aurora Sauce",fr:"Sauce Aurore",cat:"White Sauces",mo:"Velouté (poultry)",tp:"Roux-based",tm:"Hot",bs:"Poultry stock",df:"Medium",ti:"30 min",pr:["poultry","eggs","fish"],ig:{base:["supreme sauce (50cl)"],finish:["tomato fondue, very tight (50cl)"]},st:["Prepare supreme sauce.","Add very tight tomato fondue. Strain."],sm:["Supreme","Albufera"],rc:"Add 50cl of very tight tomato fondue to ½ litre supreme sauce. Strain through a sieve cheesecloth."},
    "Albufera":{nm:"Albufera Sauce",fr:"Sauce Albufera",cat:"White Sauces",mo:"Velouté (poultry)",tp:"Roux-based",tm:"Hot",bs:"Poultry stock",df:"Hard",ti:"45 min",pr:["poultry","fish","sweetbreads"],ig:{base:["supreme sauce (50cl)"],aromatics:["red bell pepper (150g)","butter (50g+150g)"],finish:["light meat glaze (5 tbsp)"]},st:["Sweat seeded pepper strips in 50g butter. Cool, blend, add 150g butter, strain.","Add meat glaze and 1 tbsp pepper butter to supreme sauce.","Strain through muslin-lined chinois."],sm:["Supreme","Aurora"],rc:"Prepare a supreme sauce. Make pepper butter by sweating 150g seeded bell pepper strips in 50g butter, cooling, blending, adding 150g butter and straining. To 50cl supreme sauce, add 5 tbsp light meat glaze and 1 tbsp pepper butter. Strain."},
    "Bercy Fish":{nm:"Bercy Sauce (Fish)",fr:"Sauce Bercy Poisson",cat:"White Sauces",mo:"Velouté (fish)",tp:"Roux-based",tm:"Hot",bs:"Fish stock",df:"Medium",ti:"25 min",pr:["fish","seafood"],ig:{base:["fish velouté (20cl)","fish fumet (10cl)","white wine (10cl)"],aromatics:["shallots (3–4), finely chopped"],finish:["butter, softened (50g)","parsley, chopped"]},st:["Sweat shallots in butter without coloring.","Deglaze with wine and fumet, reduce by half.","Add fish velouté, boil briefly. Off heat, swirl in butter, add parsley."],sm:["Normandy","Cardinal"],rc:"Sweat 3–4 finely chopped shallots in butter without coloring. Deglaze with 10cl white wine and 10cl fish fumet; reduce by half. Add 20cl fish velouté and boil briefly. Off the heat, incorporate 50g softened butter, swirl, and add chopped parsley."},
    "Tomato":{nm:"Tomato Sauce",fr:"Sauce Tomat",cat:"Brown Sauces",mo:"Tomat",tp:"Tomato-based",tm:"Hot",bs:"White stock/Tomato",df:"Easy",ti:"2 hrs",pr:["pasta","meat","vegetables","eggs"],ig:{base:["fresh tomatoes (2kg)","white stock (1L)","flour (60g)"],aromatics:["carrot (100g)","onion (100g)","garlic (2 cloves)","bouquet garni","lean ham (150g)","pork belly (100g)"],finish:["butter","sugar (20g)","salt","pepper"]},st:["Brown pork belly in butter. Add carrot, onion. Add flour, cook blond.","Add tomatoes, garlic, bouquet, ham, stock, sugar, seasoning.","Cover, simmer 2 hours.","Remove aromatics, pass through fine chinois, finish with butter."],rc:"Brown 100g diced pork belly in butter. Add 100g each diced carrot and onion. Add 60g flour, cook blond. Add 2kg crushed tomatoes, 2 garlic cloves, 1 bouquet garni, 150g lean ham, 1 litre white stock, salt, pepper, 20g sugar. Cover and simmer 2 hours. Remove aromatics, pass through fine chinois, finish with lukewarm melted butter."},
    "Bolognese":{nm:"Bolognese Sauce",fr:"Sauce Bolognaise",cat:"Brown Sauces",mo:"Tomato",tp:"Tomato-based",tm:"Hot",bs:"Brown veal stock",df:"Easy",ti:"2.5 hrs",pr:["pasta","gnocchi","polenta"],ig:{base:["braising beef (500g)","fresh tomatoes"],aromatics:["onions (5)","celery (4 stalks)","garlic (4–5 cloves)","bouquet garni","sage","rosemary"],finish:["brown veal stock (35cl)","dry white wine (20cl)","olive oil (5 tbsp)"]},st:["Brown meat in olive oil. Add onions, celery, garlic.","Add crushed tomatoes, melt 10 min.","Add bouquet, stock, wine, seasoning. Cover, simmer 2 hours."],rc:"Brown 500g roughly chopped braising beef in 5 tbsp olive oil. Add 5 chopped onions, 4 celery stalks, 4–5 garlic cloves. Add crushed tomatoes and melt 10 min. Add bouquet garni with sage and rosemary, 35cl brown veal stock, 20cl dry white wine. Cover and cook 2 hours over very low heat."},
    "Chasseur":{nm:"Chasseur Sauce",fr:"Sauce Chasseur",cat:"Brown Sauces",mo:"Brown poultry stock",tp:"Reduction",tm:"Hot",bs:"Brown veal stock",df:"Medium",ti:"30 min",pr:["chicken","rabbit","veal","pork"],ig:{base:["brown veal stock, tomatoed (40cl)","mushrooms (150g)","cognac (4cl)"],aromatics:["shallots (2)","white wine (10cl)"],finish:["butter (30g)","tarragon, chervil, parsley (1 tbsp)"]},st:["Brown chopped mushrooms and shallots in butter.","Add white wine, reduce by half. Flambé with cognac.","Add tomatoed veal stock, reduce 10 min. Finish with butter and herbs."],rc:"Chop 150g mushrooms and 2 shallots. Brown in butter, add 10cl white wine and reduce by half. Flambé with 4cl cognac. Add 40cl lightly bound tomatoed brown veal stock. Reduce gently 10 min, add 30g butter and 1 tbsp chopped herbs."},
    "Robert":{nm:"Robert Sauce",fr:"Sauce Robert",cat:"Brown Sauces",mo:"Espagnole",tp:"Reduction",tm:"Hot",bs:"Espagnole/Demi-glace",df:"Medium",ti:"30 min",pr:["pork","grilled meats","offal"],ig:{base:["espagnole or demi-glace (½ quart)"],aromatics:["onions, finely chopped (2)","butter (25g)"],acid:["white wine (20cl)","vinegar (10cl)"],finish:["white mustard (1 tbsp)"]},st:["Brown finely chopped onions in butter.","Add wine and vinegar, reduce almost dry.","Add demi-glace. Off heat, add mustard diluted with sauce."],sm:["Bordelaise","Diable"],rc:"Brown 2 finely chopped onions in 25g butter. Add 20cl white wine and 10cl vinegar; reduce almost dry. Add ½ quart espagnole or demi-glace. Off the heat, dilute 1 tbsp white mustard with a little sauce and add to the rest. Tamponner."},
    "Diable":{nm:"Diable Sauce",fr:"Sauce Diable",cat:"Brown Sauces",mo:"Demi-glace",tp:"Reduction",tm:"Hot",bs:"Demi-glace",df:"Medium",ti:"25 min",pr:["grilled chicken","grilled meats","offal"],ig:{base:["tomatoed demi-glace (20cl)"],aromatics:["shallot (1 tbsp)","white wine (15cl)","vinegar (1 tbsp)","thyme","bay leaf"],acid:["black pepper (generous)"],finish:["fine herbs, chopped (1 tbsp)"]},st:["Reduce wine, vinegar, shallot, thyme, bay, pepper by ⅔.","Add tomatoed demi-glace, reduce 5 min. Strain.","Add chopped fine herbs at last moment."],rc:"Reduce 15cl dry white wine, 1 tbsp vinegar, 1 tbsp finely chopped shallot, 1 sprig thyme, ¼ bay leaf and generous pepper by two-thirds. Add 20cl tomatoed demi-glace, reduce 5 min over low heat. Strain. Add 1 tbsp of chopped fine herbs."},
    "Poivrade":{nm:"Poivrade Sauce",fr:"Sauce Poivrade",cat:"Brown Sauces",mo:"Espagnole/Game",tp:"Reduction",tm:"Hot",bs:"Demi-glace/Game",df:"Hard",ti:"1 hr",pr:["venison","game","wild boar","hare"],ig:{base:["demi-glace or game stock (1L)"],aromatics:["carrot tops (150g)","onions (100g)","pork belly (100g)","celery (50g)","thyme","bay leaf"],acid:["vinegar (30cl)","marinade (20cl)"],finish:["peppercorns (10, crushed)","butter","cayenne"]},st:["Sweat diced mirepoix 20 min in butter with thyme, bay, pepper.","Add vinegar and marinade, reduce by half.","Add stock, simmer 30 min. Add crushed pepper, infuse 5 min. Strain."],dv:["Grand Veneur"],rc:"Dice carrot tops, onions, pork belly and celery. Sweat 20 min in butter with thyme, bay leaf and mignonnette. Add 30cl vinegar and 20cl marinade; reduce by half. Add 1 litre demi-glace or game stock, simmer 30 min. Add 10 crushed peppercorns, infuse 5 min. Strain and tamponner."},
    "Grand Veneur":{nm:"Grand Veneur Sauce",fr:"Sauce Grand Veneur",cat:"Brown Sauces",mo:"Poivrade",tp:"Reduction",tm:"Hot",bs:"Poivrade/Game",df:"Hard",ti:"1 hr",pr:["venison","game","wild boar"],ig:{base:["poivrade sauce (from venison trimmings, min 20cl)"],finish:["redcurrant jelly (1 tbsp)","crème fraîche (2 tbsp)"]},st:["Reduce poivrade sauce with venison trimmings to at least 20cl. Strain.","Gently whisk in redcurrant jelly and crème fraîche."],sm:["Poivrade","Cumberland"],rc:"Reduce a poivrade sauce made with venison trimmings to at least 20cl. Strain, then gently whisk in 1 tbsp redcurrant jelly and 2 tbsp crème fraîche."},
    "Périgueux":{nm:"Périgueux Sauce",fr:"Sauce Périgueux",cat:"Brown Sauces",mo:"Demi-glace",tp:"Reduction",tm:"Hot",bs:"Demi-glace",df:"Hard",ti:"30 min",pr:["beef","veal","foie gras","eggs"],ig:{base:["rich demi-glace (75cl)"],aromatics:["chopped truffles (100g)"],finish:["truffle essence (15cl)"]},st:["Reduce rich demi-glace.","Add truffle essence and chopped truffles."],sm:["Madeira"],rc:"Add to 75cl of rich, concentrated demi-glace 15cl of truffle essence and 100g of chopped truffles."},
    "Mayonnaise":{nm:"Mayonnaise",fr:"Mayonnaise",cat:"Cold Emulsified",mo:"Mayonnaise",tp:"Cold Emulsified",tm:"Cold",bs:"—",df:"Easy",ti:"10 min",pr:["fish","seafood","eggs","vegetables","cold meats"],ig:{base:["egg yolk (1)","oil (25cl)"],acid:["vinegar (1cl)","mustard (5g)"],finish:["fine salt","freshly ground pepper"]},st:["Whisk egg yolk with mustard, vinegar, salt and pepper.","Incorporate oil gradually while whisking constantly."],dv:["Remoulade","Tartar","Gribiche"],sm:["Remoulade","Tartar","Aioli"],rc:"Whisk 1 egg yolk with 5g mustard, 1cl vinegar, fine salt and pepper. Incorporate 25cl oil gradually while whisking constantly until emulsified."},
    "Remoulade":{nm:"Remoulade Sauce",fr:"Sauce Rémoulade",cat:"Cold Emulsified",mo:"Mayonnaise",tp:"Cold Emulsified",tm:"Cold",bs:"Mayonnaise",df:"Easy",ti:"15 min",pr:["crab","shrimp","fish","cold meats"],ig:{base:["egg yolk (1)","oil (25cl)","mustard (10g)"],aromatics:["chervil (1 tbsp)","tarragon (1 tbsp)","parsley","chives"],acid:["vinegar (1cl)"],finish:["gherkins, chopped (20g)","capers (10g)","anchovy essence"]},st:["Prepare mayonnaise with 10g mustard.","Add chopped herbs, capers, gherkins and anchovy essence."],sm:["Tartar","Mayonnaise","Gribiche"],rc:"Prepare a mayonnaise with 25cl oil. Add 2 finely diced gherkins, 2 tbsp chopped herbs, 1 tbsp drained capers and a few drops of anchovy essence."},
    "Tartar":{nm:"Tartar Sauce",fr:"Sauce Tartare",cat:"Cold Emulsified",mo:"Mayonnaise",tp:"Cold Emulsified",tm:"Cold",bs:"Mayonnaise (hard-boiled)",df:"Easy",ti:"15 min",pr:["fried fish","seafood","cold meats"],ig:{base:["hard-boiled egg yolk (1)","oil (25cl)","mustard (10g)"],aromatics:["chervil (1 tbsp)","tarragon (1 tbsp)","spring onion","chives"],acid:["vinegar (1cl)"],finish:["capers (10g)","gherkins (20g)","sweet onion (45g)"]},st:["Prepare mayonnaise using hard-boiled egg yolk.","Add chives, spring onion, capers, parsley, chervil and tarragon."],sm:["Remoulade","Gribiche"],rc:"Prepare a mayonnaise by replacing the raw egg yolk with hard-boiled egg yolk. Add chopped chives, spring onion, capers, parsley, chervil and tarragon."},
    "Gribiche":{nm:"Gribiche Sauce",fr:"Sauce Gribiche",cat:"Cold Emulsified",mo:"Mayonnaise",tp:"Cold Emulsified",tm:"Cold",bs:"Egg-based",df:"Easy",ti:"15 min",pr:["cold fish","offal","vegetables","eggs"],ig:{base:["barely hard-boiled egg yolk (1)","oil (25cl)"],aromatics:["parsley (1 tbsp)","tarragon (1 tbsp)","chervil"],acid:["vinegar (2 tbsp)"],finish:["capers or gherkins (1 tbsp)","hard-boiled egg white, julienne"]},st:["Mash barely hard-boiled egg yolk to fine paste. Whisk gradually with oil.","Add vinegar, salt, pepper, capers/gherkins, herbs and egg white julienne."],sm:["Tartar","Remoulade"],rc:"Mash 1 barely hard-boiled egg yolk to a very fine paste. Whisk little by little with 25cl oil. Add 2 tbsp vinegar, capers or gherkins, chopped parsley, chervil and tarragon, and egg white julienne."},
    "Vinaigrette":{nm:"Classic Vinaigrette",fr:"Sauce Vinaigrette",cat:"Cold Emulsified",mo:"Vinaigrette",tp:"Unstable Emulsion",tm:"Cold",bs:"—",df:"Easy",ti:"5 min",pr:["salads","vegetables","fish","cold meats"],ig:{base:["oil(s) (15cl)"],aromatics:["shallot (optional)","herbs (optional)"],acid:["vinegar(s) (5cl)"],finish:["fine salt","freshly ground pepper"]},st:["Dissolve salt in vinegar.","Whisk in oil. Season with pepper."],dv:["Mustard Vinaigrette","Ravigote"],rc:"Mix 5cl vinegar(s) with fine salt and freshly ground pepper. Whisk in 15cl oil(s). Add optional aromatics."},
    "Ravigote":{nm:"Ravigote Sauce",fr:"Sauce Ravigote",cat:"Cold Emulsified",mo:"Vinaigrette",tp:"Unstable Emulsion",tm:"Cold",bs:"—",df:"Easy",ti:"10 min",pr:["offal","fish","cold meats","vegetables"],ig:{base:["oil (30cl)","vinegar (10cl)"],aromatics:["chervil (½ tsp)","chives (½ tsp)","tarragon (½ tsp)","parsley (½ tsp)","white onion (45g)","capers (20g)"],acid:["white mustard (1 tbsp)"],finish:["fine salt","white pepper"]},st:["Prepare vinaigrette with mustard.","Stir in very finely chopped white onion, capers and herbs."],rc:"Prepare a vinaigrette with 10cl vinegar, 30cl oil, 1 tbsp white mustard. Stir in 30g very finely chopped white onions, 2 tsp small capers and chopped herbs."},
    "Cumberland":{nm:"Cumberland Sauce",fr:"Sauce Cumberland",cat:"Cold Sauces",mo:"—",tp:"Fruit-based",tm:"Cold",bs:"Redcurrant jelly",df:"Easy",ti:"20 min",pr:["game","venison","ham","duck","lamb"],ig:{base:["redcurrant jelly (20cl)","port (10cl)"],aromatics:["shallot, blanched (1 tsp)","orange zest julienne (2 tsp)"],acid:["orange juice (1)","lemon juice (1)"],finish:["mustard (1 tbsp)","salt","cayenne"]},st:["Blanch shallot and zests. Mix with mustard.","Melt jelly, add port and citrus juices. Bring to boil. Strain.","Add cooked julienne."],sm:["Yorkshire","Grand Veneur"],rc:"Blanch 1 tsp chopped shallot and julienned orange and lemon zest. Mix with 1 tbsp mustard. Melt 20cl redcurrant jelly and add with 10cl port, juice of 1 orange and 1 lemon. Season with salt and cayenne."},
    "Caramel":{nm:"Caramel Sauce",fr:"Sauce Caramel",cat:"Dessert Sauces",mo:"—",tp:"Dessert",tm:"Hot/Cold",bs:"Sugar",df:"Easy",ti:"15 min",pr:["ice cream","crêpes","apple tart","panna cotta"],ig:{base:["powdered sugar (100g)","liquid cream (120g)"],finish:["semi-salted butter (20g)"]},st:["Melt sugar to caramel. Add butter.","Add boiled liquid cream. Reboil briefly."],rc:"Melt 100g powdered sugar until caramel. Add 20g semi-salted butter, then 120g boiled liquid cream. Reboil briefly."},
    "Blackcurrant":{nm:"Blackcurrant Sauce",fr:"Sauce au Cassis",cat:"Dessert Sauces",mo:"—",tp:"Dessert",tm:"Cold",bs:"Fruit",df:"Easy",ti:"15 min",pr:["ice cream","panna cotta","cheesecake","sorbet"],ig:{base:["blackcurrants (250g)","sugar cubes (~10)"],acid:["lemon juice (1)"],finish:["water (7cl)"]},st:["Melt sugar cubes in 7cl water, boil to syrup.","Crush blackcurrants in blender, pass through fine sieve.","Mix syrup with purée. Add lemon juice."],rc:"Melt about 10 sugar cubes in 7cl water; boil to a syrup. Crush 250g blackcurrants in a blender, pass through a fine sieve. Mix syrup with fruit purée, adding juice of 1 lemon."},
    "Chocolate":{nm:"Chocolate Sauce",fr:"Sauce Chocolat",cat:"Dessert Sauces",mo:"—",tp:"Dessert",tm:"Hot/Cold",bs:"Chocolate",df:"Easy",ti:"20 min",pr:["ice cream","profiteroles","pears","crêpes"],ig:{base:["dark chocolate, chopped (130g)","water (25cl)","heavy cream (12.5cl)"],finish:["granulated sugar (70g)"]},st:["Combine all ingredients, bring to boil stirring.","Reduce over low heat until coats back of spoon.","Cool to room temperature."],rc:"Bring to boil 130g chopped dark chocolate, 25cl water, 70g granulated sugar and 12.5cl heavy cream, stirring. Reduce over low heat until the sauce coats the back of a spoon. Cool to room temperature."}
  }
};
